nyc_taxi_dev:
  outputs:
    dev:
      catalog: nyc_taxi_dev
      host: dbc-62715d28-1527.cloud.databricks.com
      http_path: /sql/1.0/warehouses/394b5a7c5de9562f
      schema: source
      threads: 1
      token: dapi939bd76f55c7454bee4ac0fbb1b9a609
      type: databricks
  target: dev
